CREATE TABLE BASE
(ID_BASE INT PRIMARY KEY,
B_NAME VARCHAR(100),
REGION VARCHAR(100),
CITY VARCHAR(100),
ADRESS VARCHAR(100),
PHONE_NUMBER INT);

CREATE TABLE CAR
(ID_CAR INT PRIMARY KEY,
ID_BASE INT FOREIGN KEY REFERENCES BASE(ID_BASE), 
MARK VARCHAR(50),
C_MODEL VARCHAR(50),
REGISTRATION_NUMBER VARCHAR(20),
PRODUCTION_YEAR DATE,
RENT_PRICE INT,
C_CATEGORY VARCHAR(50));

CREATE TABLE CLIENTS
(ID_CLIENT INT PRIMARY KEY,
C_NAME VARCHAR(20),
SURNAME VARCHAR(20),
PHONE_NUMBER INT,
ADRESS VARCHAR(50));

CREATE TABLE ORDERS
(ID_ORDER INT PRIMARY KEY,
ID_CLIENT INT FOREIGN KEY REFERENCES CLIENTS(ID_CLIENT),
ID_CAR INT FOREIGN KEY REFERENCES CAR(ID_CAR),
ORDER_DATE DATE,
RENT_START_DATE DATE,
RENT_END_DATE DATE);

CREATE TABLE ORDERS_ARCHIVE
(ID_ORDER INT PRIMARY KEY,
ID_CLIENT INT FOREIGN KEY REFERENCES CLIENTS(ID_CLIENT),
ID_CAR INT FOREIGN KEY REFERENCES CAR(ID_CAR),
ORDER_DATE DATE,
RENT_START_DATE DATE,
RENT_END_DATE DATE,
DELETE_DATE DATE);

CREATE TABLE AGENTS
(ID_AGENT INT PRIMARY KEY,
ID_BASE INT FOREIGN KEY  REFERENCES BASE(ID_BASE),
A_NAME VARCHAR(20),
SURNAME VARCHAR(20),
PHONE_NUMBER INT,
SALARY INT);

CREATE TABLE MECHANICS
(ID_MECHANIC INT PRIMARY KEY,
ID_BASE INT FOREIGN KEY REFERENCES BASE(ID_BASE),
M_NAME VARCHAR(20),
SURNAME VARCHAR(20),
PHONE_NUMBER INT,
HIREDATE DATE,
SALARY INT);

CREATE TABLE REPAIRS
(ID_REPAIR INT PRIMARY KEY,
ID_CAR INT FOREIGN KEY REFERENCES CAR(ID_CAR),
ID_MECHANIC INT FOREIGN KEY REFERENCES MECHANICS(ID_MECHANIC),
REAPAIR_DATE DATE, 
COSTS INT);