--not allowing to insert or update salary such that it would have salary lower than 200$
CREATE TRIGGER TOO_LOW_SAL ON AGENTS
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @SAL INT;
	SELECT @SAL = SALARY FROM INSERTED;
	
	IF @SAL<200 ROLLBACK;
END;


--archiving deleted orders
CREATE TRIGGER ARCHIVE_ORDERS ON ORDERS
FOR DELETE
AS
BEGIN
	DECLARE @ID INT;
	DECLARE @CLIENT INT;
	DECLARE @CAR INT;
	DECLARE @ODATE DATE;
	DECLARE @RSDATE DATE;
	DECLARE @REDATE DATE;
	DECLARE @DDATE DATE;

	SELECT @ID = (SELECT ISNULL(MAX(ID_ORDER),0)+1 FROM ORDERS_ARCHIVE);
	SELECT @CLIENT = ID_CLIENT FROM DELETED;
	SELECT @CAR = ID_CAR FROM DELETED;
	SELECT @ODATE = ORDER_DATE FROM DELETED;
	SELECT @RSDATE = RENT_START_DATE FROM DELETED;
	SELECT @REDATE = RENT_END_DATE FROM DELETED;
	SELECT @DDATE = SYSDATETIME();

	INSERT INTO ORDERS_ARCHIVE VALUES(@ID, @CLIENT, @CAR, @ODATE, @RSDATE, @REDATE, @DDATE);
END;


--printing message about number of clients after inserting any
CREATE TRIGGER MESSAGE1 ON  CLIENTS
FOR INSERT
AS
BEGIN
	DECLARE @NR INT;
	EXECUTE @NR = NR_OF_CLIENTS;
	PRINT ('1 NEW CLIENT ADDED TO DATABASE. '+'THERE ARE '+CAST(@NR AS VARCHAR(10))+' CLIENTS IN THE DATABASE NOW');
END;